export const NY_LOCATIONS: Record<string, string[]> = {
  "Albany": [],
  "Allegany": [],
  "Bronx": [],
  "Broome": [],
  "Cattaraugus": ["Olean", "Salamanca"],
  "Cayuga": ["Auburn"],
  "Chautauqua": [],
  "Chemung": [],
  "Chenango": ["Norwich"],
  "Clinton": [],
  "Columbia": [],
  "Cortland": [],
  "Delaware": [],
  "Dutchess": [],
  "Erie": [],
  "Essex": [],
  "Franklin": [],
  "Fulton": ["Gloversville", "Johnstown"],
  "Genesee": [],
  "Greene": [],
  "Hamilton": [],
  "Herkimer": [],
  "Jefferson": [],
  "Kings": [],
  "Lewis": [],
  "Livingston": [],
  "Madison": ["Oneida"],
  "Monroe": [],
  "Montgomery": [],
  "Nassau": [],
  "New York": [],
  "Niagara": [],
  "Oneida": ["Rome", "Utica"],
  "Onondaga": [],
  "Ontario": [],
  "Orange": [],
  "Orleans": [],
  "Oswego": ["Oswego"],
  "Otsego": [],
  "Putnam": [],
  "Queens": [],
  "Rensselaer": [],
  "Richmond": [],
  "Rockland": [],
  "Saratoga": ["Saratoga Springs"],
  "Schenectady": [],
  "Schoharie": [],
  "Schuyler": [],
  "Seneca": [],
  "St. Lawrence": ["Ogdensburg"],
  "Steuben": [],
  "Suffolk": [],
  "Sullivan": [],
  "Tioga": [],
  "Tompkins": ["Ithaca"],
  "Ulster": [],
  "Warren": ["Glens Falls"],
  "Washington": [],
  "Wayne": [],
  "Westchester": ["Mount Vernon", "New Rochelle", "White Plains", "Yonkers"],
  "Wyoming": [],
  "Yates": []
};

export const COUNTY_OPTIONS = Object.keys(NY_LOCATIONS).sort();